[package]
name = "ootx"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Inspection and validation CLI for OoT ROM data"

[dependencies]
oot_import.workspace = true
oot_game.workspace = true
eng_gfx.workspace = true
eng_gbi.workspace = true
eng_anim.workspace = true
eng_collision.workspace = true
eng_audio.workspace = true
oot_extract.workspace = true
anyhow.workspace = true
clap.workspace = true
glam.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
image.workspace = true
